DROP TABLE reviewshilling.category;
CREATE TABLE reviewshilling.category
(
ID INT NOT NULL AUTO_INCREMENT,
cname VARCHAR(255) NOT NULL DEFAULT "",
PRIMARY KEY (ID)
);

DROP TABLE reviewshilling.product;
CREATE TABLE reviewshilling.product
(
ID INT NOT NULL AUTO_INCREMENT,
PID VARCHAR(100) NOT NULL UNIQUE,
CID INT NOT NULL,
PNAME VARCHAR(2000) NOT NULL DEFAULT "",
IMURL VARCHAR(2000) NOT NULL DEFAULT "",
PRIMARY KEY (ID)
);

DROP TABLE reviewshilling.review;
CREATE TABLE reviewshilling.review
(
-- meta data
ID INT NOT NULL AUTO_INCREMENT,
PID VARCHAR(100) NOT NULL,
PRANK INT NOT NULL DEFAULT 0,
PPRICE  FLOAT NOT NULL DEFAULT 0.0,
RID VARCHAR(100) NOT NULL,
RNAME VARCHAR(500) NOT NULL,
FCOUNT INT NOT NULL DEFAULT 0,
HCOUNT INT NOT NULL DEFAULT 0,
SCORE INT NOT NULL DEFAULT 0,
TLEN INT NOT NULL DEFAULT 0,
WLEN INT NOT NULL DEFAULT 0,
RTEXT TEXT,
UTIME INT NOT NULL DEFAULT 0,
-- calculated from text and meta data
DTIME INT NOT NULL DEFAULT 0,
NPOS INT NOT NULL DEFAULT 0,
PPOS INT NOT NULL DEFAULT 0,
AFINN FLOAT NOT NULL DEFAULT 0.0,
IMX FLOAT NOT NULL DEFAULT 0.0,
INX FLOAT NOT NULL DEFAULT 0.0,
IMWORDS VARCHAR(10000),
INWORDS VARCHAR(10000),
-- prediction related
TRAIN INT NOT NULL DEFAULT 0,
EVALUATE INT NOT NULL DEFAULT 0,
TRUTH INT,
PRIMARY KEY (ID)
);

